name: Elixir CI

on: push

jobs:
  build:
    name: Test on Elixir ${{ matrix.elixir_version }}
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        elixir_version: ["1.10", "1.9", "1.8"]
    container:
      image: elixir:${{ matrix.elixir_version }}
    steps:
    - uses: actions/checkout@master
    - name: Install Dependencies
      run: |
        mix local.rebar --force
        mix local.hex --force
        mix do deps.get, deps.compile
    - name: Run Tests
      run: mix coveralls.json
    - name: Publish coverage
      run: curl -s https://codecov.io/bash | bash /dev/stdin -F elixir_$(echo ${{ matrix.elixir_version }} | tr . _)
      env:
        CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}

  # Disable Dialyzer testing until GitHub Actions do not have support for
  # caching as otherwise it takes **a lot** of time
  # dialyzer:
  #   name: Check Dialyzer report
  #   runs-on: ubuntu-latest
  #   container:
  #     image: elixir:1.9
  #   steps:
  #   - uses: actions/checkout@master
  #   - name: Install Dependencies
  #     run: |
  #       mix local.rebar --force
  #       mix local.hex --force
  #       mix do deps.get, deps.compile
  #   - name: Run Dialyzer
  #     run: mix dialyzer

  credo:
    name: Check formatting
    runs-on: ubuntu-latest
    container:
      image: elixir:1.9
    steps:
    - uses: actions/checkout@master
    - name: Install Dependencies
      run: |
        mix local.rebar --force
        mix local.hex --force
        mix do deps.get, deps.compile
    - name: Check formatting
      run: mix format --check-formatted
    - name: Run Credo
      run: mix credo
